# ===================================================================
# Spring Boot Base Configuration
# ===================================================================
server:
  port: 9001

# ===================================================================
# Spring Framework Configuration
# ===================================================================
spring:
  # Database Configuration (Development Default)
  datasource:
    url: jdbc:mysql://localhost:3306/custmax_official
    username: root
    password: rootpassword

  # Mail Configuration (Common)
  mail:
    host: smtp.larksuite.com
    port: 465
    username: hello@custmax.com
    password: 2ZmJgBKYrs6yNRp5
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: false
          ssl.enable: true
          socketFactory.class: javax.net.ssl.SSLSocketFactory
          timeout: 30000
          connection timeout: 10000
          writetimeout: 10000

  # AI Configuration (Common)
  ai:
    openai:
      model: gpt-3.5-turbo
      api-key: your_api_key_here

# ===================================================================
# MyBatis Configuration
# ===================================================================
mybatis:
  mapper-locations: classpath:mapper/*.xml

# ===================================================================
# CORS Configuration (Development Default)
# ===================================================================
cors:
  allowed-origins: http://localhost:3000
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers:
    - "*"
  allow-credentials: true


# ===================================================================
# Payment Configuration (Common)
# ===================================================================
stripe:
  public-key: ${STRIPE_PUBLISHABLE_KEY:pk_test_default}
  secret-key: ${STRIPE_SECRET_KEY:sk_test_default}
  success-url: ${website.full-url}/payment/success
  cancel-url: ${website.full-url}/payment/cancel

# ===================================================================
# Business Domain Configuration
# ===================================================================
domain:
  email-receiver: 1453631832@qq.com

# ===================================================================
# Website Configuration
# ===================================================================
website:
  wpcli:
    host: 172.237.149.194
    path: /var/www/wordpress
  full-url: http://localhost:3000